export const CATEGORIES = [
  { label: 'ทั้งหมด', key: '전체', imgUrl: '/images/categories/all.png' },
  { label: 'ร้านใหม่', key: '신규맛집', imgUrl: '/images/categories/new.png' },
  { label: 'สั่ง 1 คน', key: '1인분주문', imgUrl: '/images/categories/1.png' },
  { label: 'ไก่ทอด', key: '치킨', imgUrl: '/images/categories/chicken.png' },
  { label: 'เบอร์เกอร์', key: '버거', imgUrl: '/images/categories/burger.png' },
  { label: 'อาหารเกาหลี', key: '한식', imgUrl: '/images/categories/korean.png' },
  { label: 'ทงคัตสึ', key: '일식돈까스', imgUrl: '/images/categories/cutlet.png' },
  { label: 'จกบัล/โพซัม', key: '족발보쌈', imgUrl: '/images/categories/jokbal.jpg' },
  { label: 'อาหารจีน', key: '중식', imgUrl: '/images/categories/chinese.png' },
  { label: 'สแน็คบาร์', key: '분식', imgUrl: '/images/categories/snackbar.png' },
  { label: 'อาหารเอเชีย', key: '아시안', imgUrl: '/images/categories/asian.png' },
  { label: 'พิซซ่า', key: '피자양식', imgUrl: '/images/categories/pizza.png' },
  { label: 'กาแฟ/เค้ก', key: '카페디저트', imgUrl: '/images/categories/cake.png' },
  { label: 'สลัด', key: '샐러드', imgUrl: '/images/categories/salad.png' },
  { label: 'อาหารง่ายๆ', key: '도시락죽', imgUrl: '/images/categories/slowfood.png' },
  { label: 'จิมทัง', key: '찜탕', imgUrl: '/images/categories/soup.png' },
  { label: 'เนื้อ', key: '고기구이', imgUrl: '/images/categories/pork-belly.png' },
  { label: 'ซาซิมิ/ซูชิ', key: '회초밥', imgUrl: '/images/categories/sushi.png' },
  { label: 'แซนวิช', key: '샌드위치', imgUrl: '/images/categories/sandwich.png' },
  { label: 'อาหารว่าง', key: '야식', imgUrl: '/images/categories/late-night.png' },
  { label: 'แฟรนไชส์', key: '프랜차이즈', imgUrl: '/images/categories/chain.png' },
  { label: 'ร้านสะดวก', key: '편의점', imgUrl: '/images/categories/convenience-store.png' },
  { label: 'ชานมไข่มุก/ชานม', key: '버블티', imgUrl: '/images/categories/Gong_Cha.png' },
  { label: 'ซูปมาลา', key: '마라탕', imgUrl: '/images/categories/mara.png' },
  { label: 'ซุปกระดูกหมู', key: '감자탕', imgUrl: '/images/categories/Gamjatang-.png' },
  { label: 'ปูดองซีอิ๊ว', key: '간장게장', imgUrl: '/images/categories/ganjang.png' },
]
