export const CATEGORIES = [
  { label: 'ทั้งหมด', key: '전체', imgUrl: '/images/categories/all.png' },
  { label: 'ไก่ทอด', key: '치킨', imgUrl: '/images/categories/chicken2.png' },
  { label: 'พิซซ่า', key: '피자양식', imgUrl: '/images/categories/img_pizza.png' },
  { label: 'เบอร์เกอร์', key: '버거', imgUrl: '/images/categories/burger2.png' },
  { label: 'กาแฟ/เค้ก', key: '카페디저트', imgUrl: '/images/categories/cake2.png' },
  { label: 'ชานมไข่มุก', key: '밀크티', imgUrl: '/images/categories/Cha32.png' },
  { label: 'ชีสบอล', key: '치즈볼', imgUrl: '/images/categories/cheez2.png' },
  { label: 'ทาโกะยากิ', key: '타코야끼', imgUrl: '/images/categories/taco3.png' },
  { label: 'ซาซิมิ/ซูชิ', key: '회초밥', imgUrl: '/images/categories/sushi2.png' },
  { label: 'จกบัล', key: '족발보쌈', imgUrl: '/images/categories/jokbal2.jpg' },
  { label: 'อาหารจีน', key: '중식', imgUrl: '/images/categories/zzam2.png' },
  { label: 'เนื้อ', key: '고기구이', imgUrl: '/images/categories/pork-belly2.png' },
  { label: 'อาหารเกาหลี', key: '한식', imgUrl: '/images/categories/korean2.png' },
  { label: 'ซุปกระดูกหมู', key: '감자탕', imgUrl: '/images/categories/Gamjatang-.png' },
  { label: 'ซูปมาลา', key: '마라탕', imgUrl: '/images/categories/mara2.png' },
  { label: 'ปูดองซีอิ๊ว', key: '간장게장', imgUrl: '/images/categories/ganjang.png' },
  { label: 'ร้านสะดวก', key: '편의점', imgUrl: '/images/categories/convenience-store2.png' },
  { label: 'อาหารไทย', key: '태국', imgUrl: '/images/categories/tah.png' },
]
